# Generated by Django 6.0.1 on 2026-01-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='status',
            field=models.CharField(choices=[('watching', 'Watching'), ('finished', 'Finished'), ('abandoned', 'Abandoned')], default='watching', max_length=10),
        ),
    ]
