# Generated by Django 6.0.1 on 2026-01-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='status',
        ),
    ]
