# Generated by Django 6.0.1 on 2026-01-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_remove_film_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
